name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.45.0"
          command: "pnpm run pages:deploy"

  migrate:
    needs: []
    runs-on: ubuntu-latest
    name: Migrate
    steps:
      - uses: actions/checkout@v4
      - name: Migrate
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.45.0"
          command: "pnpm run d1:remote:migrate"