name: Deploy

on:
  push:
    branches:
      - main

env:
  PNPM_VERSION: 10
  NODE_VERSION: '22'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    permissions:
      contents: read

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        run: pnpm run pages:deploy

      - name: Deployment status
        if: success()
        run: echo "✅ Deployment to Cloudflare Pages completed successfully"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Deployment failed. Check logs above for details"