name: Migrate

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Migrate
    steps:
      - uses: actions/checkout@v4
      - name: Migrate
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.45.0"
          command: "pnpm run d1:remote:migrate"
