name: Migrate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Migration environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production

env:
  PNPM_VERSION: 10
  NODE_VERSION: '22'

jobs:
  migrate:
    runs-on: ubuntu-latest
    name: Database Migration
    
    permissions:
      contents: read

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run database migration
        run: pnpm run d1:remote:migrate
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}

      - name: Migration completed
        if: success()
        run: echo "✅ Database migration to ${{ github.event.inputs.environment }} completed successfully"

      - name: Migration failed
        if: failure()
        run: echo "❌ Database migration failed. Check logs above for details"